---
title: "Basic R sessions for Biologist"
author: "Sangram"
date: '`r format(Sys.time(), "Last modified: %d %b %Y")`'
---

# Course Description
This course provides an introduction to the R programming language and software environment for statistical computing and graphics. A variety of examples with a biological theme will be presented.

# Prerequisites
No prior programming experience is required, but those attending should be able to use a plain text editor.
A very basic knowledge of UNIX would be an advantage, but nothing will e assumed and extremely little will be required.

# Objectives

After the course you should feel confident to start exploring your own dataset using the materials and references provided. Including things like:

* Import data and plot graphs
* Perform statistical tests in R
* Create a documented and reproducible piece of R code
* Know how to develop your skills in R after the course
* Install and use Bioconductor packages

# Aims

During this course you will learn about: 

* The RStudio interface to R
* The many ways to access help about R
* Basic object types in R
* Importing tabular data into R
* Manipulating data in R
* Using in-built functions
* Statistical testing in R
* Executing basic data analysis workflows in R
* Basic Plotting
* Customizing plots
* Basic programming with if/else statements and for loops
* Creating reproducible reports in R

# Course Structure


***
**Credits:**
This matrials are combination of one or more resources listed bellow.  
[Cambridge Basic R Course](https://github.com/cambiotraining/r-intro)  
[swcarpentry r-novice-inflammation](https://github.com/swcarpentry/r-novice-inflammation/)  