---
title: "Basic R sessions for Biologist"
author: "Sangram Keshari Sahu"
date: '`r format(Sys.time(), "Last modified: %d %b %Y")`'
---

# Course Description
This course provides an introduction to the R programming language for statistical computing and graphics. Focused with biological applications.

Although this is created based on class-sessions in mind, it can also adopted as self-learning material.

# Prerequisites
No prior programming experience is required, but those attending should be able to use a plain text editor.
A very basic knowledge of UNIX would be an advantage, but nothing will assumed and extremely little will be required.

# Objectives
After the course you should feel confident to start exploring your own dataset using the materials and references provided. Including things like:

* Import data and plot graphs
* Perform statistical tests in R
* Create a documented and reproducible piece of R code
* Know how to develop your skills in R after the course
* Install and use Bioconductor packages

# Aims

During this course you will learn about: 

* The R Studio interface to R
* The many ways to access help about R
* Basic object types in R
* Importing tabular data into R
* Manipulating data in R
* Using in-built functions
* Statistical testing in R
* Executing basic data analysis workflows in R
* Basic Plotting
* Customizing plots
* Basic programming with if/else statements and for loops
* Creating reproducible reports in R

# Course Structure

* [Introduction](intro.html) What and Whys of R
* [Session-1](session-1.html) Data Type and Data Structure
* [Session-2](session-2.html) Steps to Basic Data Analysis
* [Session-3](session-3.html) Programming in R
* [Session-4](session-4.html) Packages in R and Biocondutor
* [Session-5](session-5.html) Graphics in R
* [Extra](extra.html) Resource Links and Glossary
* [Practice](exercises-1.html) For self-exercise
* [Class Test](test-1_encrypted.html)

# Resources:
This materials are combination of one or more resources listed bellow.[^1][^2][^3]  

[^1]: [Cambridge Basic R Course](https://github.com/cambiotraining/r-intro)  
[^2]: [swcarpentry r-novice-inflammation](https://github.com/swcarpentry/r-novice-inflammation/)
[^3]: few others
  
